### PR TITLE
[Cache-Busting] Add Epoch Timestamp to asset query string

### PR DESCRIPTION
**Pull request by khanhicetea**
Hi @appernetic ,

Firstly, thanks for your work ! This is nice theme 👍

This pull request helps solving cache-busting problem, based on [this discussion](https://discourse.gohugo.io/t/cache-busting-of-css-js/175/13)

### CODE REVIEW

**Comment by appernetic** [comment]
Thanks!

That is a rather old dicussion about cache busting. Have you checked out the latest on asset pipelines in Hugo: https://gohugo.io/categories/asset-management

I will check your solution later today and see if it's better. One problem with the new asset pipeline is that you can't override css files outside the theme and that you need v 0.44. Check out how it's implemented here:  https://github.com/appernetic/hugo-bootstrap-premium

**Comment by khanhicetea** [comment]
Yah, one more problem about CSS is mostly when I want to override CSS, I have to copy original one to `static/css/` directory then update the file. But doing this, I can't update the theme CSS  when it has new update (bug fixes or new features). Tracking diffences is a bit painful !

> One problem with the new asset pipeline is that you can't override css files outside the theme and that you need v 0.44.

Could we support **backwards compatibility** by checking hugo version ?

- Using `?v={{ now.Unix }}`  on older Hugo
- Using asset pipeline on Hugo 0.44+

Thanks !

**Comment by appernetic** [comment]
Sorry for late reply. Yes that is a good solution to check version.

**Comment by appernetic** [comment]
Have you come up with a solution?

**Comment by appernetic** [comment]
You can change the assest dir: Asset directory 
Asset files must be stored in the asset directory. This is /assets by default, but can be configured via the configuration file’s assetDir key. (ref: https://gohugo.io/hugo-pipes/introduction/)

I have not tested if you can use the sites public folder as the assets dir.

**Pull request merged**
