### PR TITLE
Upgrade to Font Awesome 5.3.1 and Added YouTube Social Icon

### PR DESCRIPTION
**Pull request by MatthewMcD**
Love this theme! 

In this PR I:

- Upgraded Font Awesome to 5.3.1 and removed the dependency on local font awesome files
- I added a YouTube icon and included the option under the Site and Author parameters. 
- I cleaned up the code formatting in the `single.html` template
- I updated the screenshot and thumbnail as the older one did not show the social icons.

### CODE REVIEW

**Comment by appernetic** [comment]
Great! There is one big problem though. On mobile devices, the main menu dropdown will be over the social icons. I don't know if that was a problem before, I just saw it now when I tested your fork.

fireshot capture 11 - a post with lot of comments - http___localhost_1313_post_work8_

**Comment by MatthewMcD** [comment]
Wow, great catch. I don't use them all so I didn't notice that in my dev environment. How do you think I should handle it? CSS overflow? Is scaling possible?

**Comment by appernetic** [comment]
Maybe it's possible to just put the menu below the social icons bar, so that the menu starts after it.

**Comment by MatthewMcD** [comment]
I think I'll split this in to 2 PRs. One for the font awesome upgrade and one for youtube.

**Pull request closed without merging**
